### ISSUE TITLE
Image/lightbox glitch on Android

### ISSUE THREAD

**Issue by jacklj** [FaridSafi/react-native-gifted-chat#714] opened 2018-01-16 18:00 UTC
#### Issue Description

When you are closing the image lightbox on Android, the image shrinks down to the location of the message. However, it is going to a location vertically offset from the message's on screen location. Here's a video to explain:

![gifted chat android image glitch](https://user-images.githubusercontent.com/3493438/35003956-6e557ef2-fae6-11e7-8961-e7a503190078.gif)

#### Steps to Reproduce / Code Snippets

We are using the default image / lightbox components, nothing custom.

As you can see in the gif, we have a status bar, whearas in the example expo for the gifted-chat repo, the android app covers the status bar - could this be the source of the incorrect offset?

#### Expected Results

The image is shrunk back into the right location.

#### Additional Information

* Nodejs version: 6.10
* React version: 16.0.0-alpha.12
* React Native version: 0.45.1
* react-native-gifted-chat version: 0.3.0
* Platform(s): iOS

**Comment by xcarpentier** [comment] 2018-01-17 07:19
I think it's a react-native-lightbox issue: https://github.com/oblador/react-native-lightbox/pull/92

**Comment by jacklj** [comment] 2018-01-17 10:41
Ah thanks. Is it possible to use a custom lightbox library? Seems like the PR we need isn't being merged into lightbox.

**Comment by mafiusu** [comment] 2018-01-17 10:56
@jacklj yes you can use a custom Lightbox library. You can use renderMessageImage as a prop for the GiftedChat and there you will pass in a function that renders a MessageImage. Just have a look at the example in MessageImage.js. You can copy the code from there and change the lightbox to your needs. With renderMessageImage you will display your changed from the file.

**Comment by jacklj** [comment] 2018-01-17 10:57
OK great thanks, will give it a go!

**Comment by xcarpentier** [comment] 2018-01-17 17:16
@jacklj can close this issue or will you need it again?

**Comment by farhanmannan** [comment] 2018-06-28 15:56
I've taken over the code @jacklj was using - the issue is still there in react-native-lightbox

**Closed** 2019-02-19 16:55 UTC
Labels: waiting-response, wontfix
