### ISSUE TITLE
Height of TextInput field to small on iOS multiline

### ISSUE THREAD

**Issue by djschilling** [FaridSafi/react-native-gifted-chat#1691] opened 2020-03-18 23:26 UTC
#### Issue Description

I use the default message composer.
On Android the height of the TextInput Field is calculated correctly.
On iOS the first line is not visible entirely.

![Screenshot_1584573808](https://user-images.githubusercontent.com/3503166/77016531-35555c00-6978-11ea-9617-9a6e7b7d9349.png)
![Simulator Screen Shot - iPhone 11 - 2020-03-19 at 00 18 58](https://user-images.githubusercontent.com/3503166/77016541-3dad9700-6978-11ea-8845-d03df957c460.png)

#### Additional Information

* React Native version: 0.61.5
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by vamshi9666** [comment] 2020-03-19 12:43
+1

**Comment by claudiozam** [comment] 2020-03-23 01:11
+1

**Comment by jahanzaibhw** [comment] 2020-03-25 17:23
+1

**Comment by ivanhubs** [comment] 2020-03-30 14:05
+1

**Comment by hubermat** [comment] 2020-05-01 08:30
Possible duplicate of #1727

**Closed** 2020-06-05 10:29 UTC
Labels: wontfix

**Comment by nescroft** [comment] 2022-05-20 22:47
@vamshi9666 @djschilling going back to the npm version "react-native-gifted-chat": "^0.16.3" fixed it for me...

So, instead of installing directly from the github link I installed like this:

yarn add react-native-gifted-chat

Then:

import from 'react-native-gifted-chat' instead of 'react-native-gifted-chat/src' 

Hope that helps.

**Comment by fukemy** [comment] 2022-06-17 06:27
still problem in lasted version, height of android too big
