### ISSUE TITLE
Gifted chat doesn't show when rendering with React native testing library

### ISSUE THREAD

**Issue by OliverAThunes** [FaridSafi/react-native-gifted-chat#2192] opened 2022-04-21 14:03 UTC
#### Issue Description

I'm trying to test a component which contains a GiftedChat component.
When rendering it out the giftedChat component does not appear and I cannot actually run any tests on it.

#### Steps to Reproduce / Code Snippets

  test('Should render non-ascii characters', async () => {
    let props: any = {
      route: {
        params: { item: { id: 'IRVXrM5V6bke6jzxrCUp' } },
      },
    }
    const { debug } = render(<ChatView {...props} />)
    debug()
  })

#### Expected Results

the debug statement should show that the gifted chat is rendering.

#### Additional Information

* Nodejs version: v16.11.1
* React version: 17.0.1
* React Native version: 0.64.3
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Jest (nodejs)
* TypeScript version: 4.3.5

**Comment by Johan-dutoit** [comment] 2022-05-29 13:49
duplicate of https://github.com/FaridSafi/react-native-gifted-chat/issues/1637

**Closed by Johan-dutoit** 2022-05-29 13:49 UTC
