### ISSUE TITLE
Disorganized messages on app

### ISSUE THREAD

**Issue by rafaellaguardia** [FaridSafi/react-native-gifted-chat#1327] opened 2019-07-19 17:52 UTC
![Screenshot_20190719-145409_WeFound](https://user-images.githubusercontent.com/44610598/61555207-31fa8100-aa35-11e9-9b51-baa800b6bd1a.jpg)
My messages usually have, the main problem is when messages "load" are displayed in a random and incomprehensible order.

Look this:

loadMessages = async () => {
    const { user } = this.props;
    const matchId = this.props.navigation.getParam('matchId');
    const data = (await firebase.database().ref(`matchs/${matchId}/messages`).once('value')).val();
    
      
    let messages = [];
    if(data){
      Object.keys(data)
        .forEach(messageId => {
          let message = data[messageId];

          if(_.get(message, 'user._id') !== user.uid) _.set(message, 'user._id', 2);
          messages.push(message);

        });
    }

    this.setState(() => ({
      messages,
    
    }));

  }

#### Expected Results

Ordened messages
![Captura de tela de 2019-07-19 14-50-51](https://user-images.githubusercontent.com/44610598/61555023-c4e6eb80-aa34-11e9-834e-9329970a8795.png)
![Captura de tela de 2019-07-19 14-51-03](https://user-images.githubusercontent.com/44610598/61555024-c4e6eb80-aa34-11e9-9d4a-f9dddb8e7126.png)

**Comment by pierroo** [comment] 2019-08-28 08:41
Hello @rafaellaguardia 

I also randomly face the same issue, and have been unable to find the root cause or a fix for this.

Have you made any progress on this issue?

Please let me know if you did! :)

**Comment by evertonco** [comment] 2019-09-10 23:50
Object.keys not guarantee order of object properties. You must order tem by yourself

**Closed** 2019-11-17 01:39 UTC
Labels: wontfix
