### ISSUE TITLE
keyboard not dismissing in production

### ISSUE THREAD

**Issue by austin-sprawls** [FaridSafi/react-native-gifted-chat#330] opened 2017-01-06 19:07 UTC
#### Issue Description

The keyboard dismisses properly for Android and iOS when I test in development mode but doesn't dismiss in either Android or iOS when I release a production build to Testflight and Google Play Store.

#### Steps to Reproduce / Code Snippets

Upload a React Native app to either Testflight or Google Play Store, download, and try to click anywhere to dismiss keyboard. Will not dismiss for me.

#### Additional Information

* React Native version: 0.37.0
* react-native-gifted-chat version: 0.0.10
* Platform(s) (iOS, Android, or both?): Android and iOS in production only

**Comment by eduedix** [comment] 2017-01-27 09:42
for me the keyboard is hidden when I tap in the chat window in iOS simulator. But when I run the app on the device the behaviour is inconsistent. Tapping on chat does not dismiss the keyboard all the time but randomly.

**Comment by kfiroo** [comment] 2017-01-29 14:53
@tafelito any idea what's going on here?

**Comment by tafelito** [comment] 2017-01-29 16:34
@austin-sprawls Have you tried using the latest version of RN?

**Comment by eduedix** [comment] 2017-01-29 17:01
@tafelito yes. does the keyboard really get hidden on your iPhone, when you tap the chat view?

**Comment by tafelito** [comment] 2017-01-30 02:11
@eduedix yes indeed. I just tried on an iPhone 6 and everything works well for me. Are you running the example code?

**Comment by eduedix** [comment] 2017-01-30 07:13
@tafelito I think something got fixed about this in the latest version, as example code works now. Still the keyboard doesn't get hidden in my project where the chat window is actually a TabItem of exponent/ex-navigation. I will let you know again after trying the example code in a TabItem.

**Comment by eduedix** [comment] 2017-01-30 07:22
@tafelito FYI, the problem persists with example code on react-native-gifted-chat@0.0.10 (without TabItem etc.)

**Comment by eduedix** [comment] 2017-01-30 10:12
@tafelito The issue is resolved in react-native-gifted-chat@0.1.0 .

**Comment by kfiroo** [comment] 2017-01-30 12:59
@eduedix in `react-native-gifted-chat@0.0.10` there is no way to change `keyboardShouldPersistTaps` prop

**Closed** 2017-01-30 12:59 UTC
