### ISSUE TITLE
Breaking Issue -> Android 'Super expression must either be null or a function'

### ISSUE THREAD

**Issue by mowme** [FaridSafi/react-native-gifted-chat#1724] opened 2020-04-04 19:25 UTC
#### Issue Description
Android 'Super expression must either be null or a function' (React 0.62.0+)

Issue is that the GiftedChat library uses @expo/react-native-action-sheet 3.4.1. They released 3.6.0 to fix this issue. (https://github.com/expo/react-native-action-sheet/commits/master/src/ActionSheet/TouchableNativeFeedbackSafe.tsx)

Upgraded giftedchat package to use 3.6.0 and it fixed the issue. Thanks!

**Comment by enosh94** [comment] 2020-04-05 08:29
Duplicate of #1703

**Comment by EhteshamAnwar** [comment] 2020-04-09 15:45
> #### Issue Description
> Android 'Super expression must either be null or a function' (React 0.62.0+)
> 
> Issue is that the GiftedChat library uses @expo/react-native-action-sheet 3.4.1. They released 3.6.0 to fix this issue. (https://github.com/expo/react-native-action-sheet/commits/master/src/ActionSheet/TouchableNativeFeedbackSafe.tsx)
> 
> Upgraded giftedchat package to use 3.6.0 and it fixed the issue. Thanks!

@mowme how can I resolve this error  resolve this error

**Comment by mowme** [comment] 2020-04-09 15:53
@EhteshamAnwar it was easy to fix, but is not a long term solution. You can go into the package.json for  Gifted Chat (react-native-gifted-chat) and change the dependency for @expo/react-native-action-sheet to 3.6.0. Then run your normal npm updates/install.

You can verify that it worked by going into package-lock.json file and verifying that react-native-gifted-chat's requires & dependencies show 3.6.0 for react-native-action-sheet.

Hopefully that helps until its updated and pushed!

**Comment by aristech** [comment] 2020-04-10 10:40
Any news on the update? 
I can't make the fix work on non expo project.

**Comment by dorthwein** [comment] 2020-04-11 15:50
Another work around is to install a newer version of action sheet into your project.  You may need to install unimodules so you can use expo packages outside of an expo project.

Unimodules Pacakge: [https://github.com/unimodules/react-native-unimodules](url)
Action Sheet Package: [https://github.com/expo/react-native-action-sheet](url)

`npm install @expo/react-native-action-sheet -S`

**Comment by Amanullah22** [comment] 2020-04-20 16:32
![Screenshot_20200420-212623](https://user-images.githubusercontent.com/39756073/79775689-0bfc6700-834e-11ea-8732-a931aae8bb15.png)

I am trying to use react-native-gifted-chat, and I keep getting this run time error.
Any help would be appreciated!

My Package.json

"dependencies": {
    "@expo/react-native-action-sheet": "^3.6.0",
    "@react-native-community/masked-view": "^0.1.9",
    "core-js": "^3.6.5",
    "firebase": "^7.14.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gifted-chat": "^0.13.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.3.7",
    "react-navigation-stack": "^2.3.12",
    "teaset": "^0.7.4"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^25.3.0",
    "eslint": "^6.8.0",
    "jest": "^25.3.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }

**Comment by fahadkhan20** [comment] 2020-04-28 07:22
> #### Issue Description
> Android 'Super expression must either be null or a function' (React 0.62.0+)
> 
> Issue is that the GiftedChat library uses @expo/react-native-action-sheet 3.4.1. They released 3.6.0 to fix this issue. (https://github.com/expo/react-native-action-sheet/commits/master/src/ActionSheet/TouchableNativeFeedbackSafe.tsx)
> 
> Upgraded giftedchat package to use 3.6.0 and it fixed the issue. Thanks!

thnk you soo much bro ..i fixed my issue

**Closed** 2020-06-03 03:32 UTC
Labels: wontfix

**Comment by nabilfreeman** [comment] 2020-10-28 23:05
Bad bot
