### ISSUE TITLE
Bottom Gap after keyboard hidden

### ISSUE THREAD

**Issue by IronLady** [FaridSafi/react-native-gifted-chat#1614] opened 2020-01-18 12:31 UTC
#### Issue Description

Seems like there is some gap after keyboard close. Before and while keyboard showing, there is no gap.

1. Before keyboard shown
![Before Keyboard Shown](https://i.imgur.com/V0Ddwls.jpg)

2. Keyboard shown
![Keyboard Shown](https://i.imgur.com/sZLIXrY.jpg)

3. Keyboard hidden
![Keyboard Hidden](https://i.imgur.com/rv13Trd.jpg)

#### Steps to Reproduce / Code Snippets

```javascript
<SafeAreaView style={styles.androidSafeArea}>
    <GiftedChat
        messages={this.state.messages} 
        onSend={messages => this.onSend(messages)}
        user={{
        _id: 1,
        }} />
    <KeyboardAvoidingView behavior={'padding'} keyboardVerticalOffset={80}/>
</SafeAreaView>
```

#### Expected Results

There is no gap below the text input bar. Just like the 1st screenshot

#### Additional Information

* Nodejs version: 8
* React version: 16.9.0
* Expo React Native version: 36.0.0
* react-native-gifted-chat version: 0.13.0
* Platform(s) (iOS, Android, or both?): Android 9

**Comment by technoplato** [comment] 2020-01-18 21:39
I realize this is on Android, but possible dupe of https://github.com/FaridSafi/react-native-gifted-chat/issues/1306

**Comment by msqar** [comment] 2020-01-27 19:17
@IronLady Were you able to solve it? I just see this post of yours, it happens for instance on my iPhone XS, it looks ugly, i'd like to make it fill down the bottom too.

**Comment by IronLady** [comment] 2020-01-28 04:07
@msqar Not yet. I can't find the issue. Is it really happening in iOS too?

**Comment by msqar** [comment] 2020-01-28 11:10
@IronLady yes, i created an issue for this on iOS yesterday. Here it is so you can keep track of it if you'd like https://github.com/FaridSafi/react-native-gifted-chat/issues/1624

**Comment by msqar** [comment] 2020-01-28 15:29
@IronLady ended up fixing it myself by again, modifying GiftChat code. I have a local forked version with all my custom modifications. Had to remove the SafeAreaView and handle every case with isIphoneX() to set different heights of input toolbox and also the overall container height to prevent overlapping between message container and input toolbar. I suggest you doing the same, otherwise it will be a looong wait until something gets released in master.

**Comment by technoplato** [comment] 2020-01-28 17:20
Any chance you could post that code?

**Comment by msqar** [comment] 2020-01-28 23:27
@technoplato sure but how can i share all those files? i did modifications to some files, i added stuff like when top is reached i automatically load more messages instead of having to press the button, added the scrollToBottom to work along the feature i just mentioned otherwise both wouldn't work at the same time, and i also fixed the iPhoneX marginBottom and now it works on Android/iOS. I can't tell you exactly where i did these changes as i made them not all at once, I kept working on my own version of it.

**Comment by technoplato** [comment] 2020-01-29 00:22
If they’re in git, you can just push them to a repo of your own and link
us. We can look at the diffs from there.

If not in git, you could add them to git and push them up. We’d just have
to sort through differences with a different strategy.

**Comment by shamilovtim** [comment] 2020-01-29 05:06
@msqar you should move your changes to a fork of this project so that:

1. you could make a pull request and contribute to this project
2. (most importantly) the next time you `npm install` your changes will be overwritten permanently. they should be stored in git on a new branch off of master in your fork.

**Comment by shamilovtim** [comment] 2020-01-29 05:08
if you search existing issues you will see issues relevant to the fact that you've nested your entire project in a Safeareaview but this project provides its own Safeareview. People have already encountered and worked around this and you can consult their solutions

**Comment by technoplato** [comment] 2020-01-29 14:49
Well that definitely seems simpler. Will try, thanks Timothy.

**Comment by msqar** [comment] 2020-01-29 23:08
@shamilovtim i know, that's why my changes are in my own project, I got all the files from gifted-chat and made my own version. I should make these changes in this official repo. I will whenever I have some time.

**Closed** 2020-03-05 00:34 UTC
Labels: wontfix
