### ISSUE TITLE
EventEmitter.removeListener('keyboardDidHide', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.

### ISSUE THREAD

**Issue by FayyazAliKhan1** [FaridSafi/react-native-gifted-chat#2162] opened 2022-02-23 11:50 UTC
#### Issue Description

IOS crash when going back from gifted chat screen(using navigation.goBack()), android has also this issue but not crash
#### Steps to Reproduce / Code Snippets
![Simulator Screen Shot - iPhone 11 - 2022-02-23 at 16 45 01](https://user-images.githubusercontent.com/46970238/155313404-aa30ff9b-8ef6-4398-b512-18bd99330546.png)

Used just the basic example of gifted chat functional component, issue is not faced when I comment Gifted chat component 
[FILL THIS OUT]

#### Expected Results
At least the crash should gone
[FILL THIS OUT]

#### Additional Information

* Nodejs version: [FILL THIS OUT]
* React version: 17.0.2
* React Native version: 0.66.4
* react-native-gifted-chat version: 0.16.3
* Platform(s) (iOS, Android, or both?): Both but IOS app crashes
* TypeScript version: [FILL THIS OUT]

**Comment by imandyie** [comment] 2022-03-02 00:12
Just install directly from this repo, the issue is already fixed
`yarn add https://github.com/FaridSafi/react-native-gifted-chat`

**Comment by irodeanu** [comment] 2022-03-04 08:15
Same issue. @imandyie I tried your solution and I get this:
![Simulator Screen Shot - iPhone 13 - 2022-03-04 at 10 11 57](https://user-images.githubusercontent.com/5019858/156725337-7c9a4389-a1fb-4e0a-8cc2-f7cec3a2d5d4.png)

**Comment by imandyie** [comment] 2022-03-04 09:48
You will need to import from the src folder 
`import {GiftedChat} from 'react-native-gifted-chat/src';`

**Comment by irodeanu** [comment] 2022-03-04 15:28
> 

Now it is working 👍

**Comment by irodeanu** [comment] 2022-03-04 15:29
> You will need to import from the src folder `import {GiftedChat} from 'react-native-gifted-chat/src';`

Now it is working 👍

**Comment by ELECTRO-2006** [comment] 2022-03-06 20:49
ok i had solved this just do one thing 

**IN YOUR  MESSAGE CONTAINER.JS INSIDE NODE MODULES FOLDER **
`
this.attachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
    if (invertibleProps) {
-        Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-        Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-        Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-        Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+        this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+        this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+        this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+        this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
    }
};
this.detachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
-    Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-    Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-    Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-    Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+    this.willShowSub?.remove();
+    this.didShowSub?.remove();
+    this.willHideSub?.remove();
+    this.didHideSub?.remove();
};
`

**Comment by ELECTRO-2006** [comment] 2022-03-06 20:52
i had managed to slove this just do one thing 

**JUST DO ONE THING DO THE FOLLOWING CHANGES INSIDE MESSAGECONTAINER.JS UNDER NODEMODULES** 
```
this.attachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
    if (invertibleProps) {
-        Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-        Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-        Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-        Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+        this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
+        this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
+        this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
+        this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
    }
};
this.detachKeyboardListeners = () => {
    const { invertibleScrollViewProps: invertibleProps } = this.props;
-    Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
-    Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
-    Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
-    Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
+    this.willShowSub?.remove();
+    this.didShowSub?.remove();
+    this.willHideSub?.remove();
+    this.didHideSub?.remove();
};
```

**Comment by FayyazAliKhan1** [comment] 2022-03-07 06:17
@imandyie sorry for late check, but your solution works fine & @ELECTRO-2006  your solution works too
Thank you so much

**Comment by ELECTRO-2006** [comment] 2022-03-07 07:06
@FayyazAliKhan1  PLEASE CLOSE THE ISSUE IF SO

**Comment by FayyazAliKhan1** [comment] 2022-03-08 05:45
I am closing it, cause it's fixed,  Thanks everyone

**Closed** 2022-03-08 05:44 UTC

**Comment by fukemy** [comment] 2022-04-17 11:27
i got this error:
 react-native-gifted-chat/src could not be found within the project or in these directories:

**Comment by fukemy** [comment] 2022-04-17 11:33
im using version:
"react-native-gifted-chat": "^0.16.3",

**Comment by fukemy** [comment] 2022-04-17 11:34
> this.attachKeyboardListeners = () => {
>     const { invertibleScrollViewProps: invertibleProps } = this.props;
>     if (invertibleProps) {
> -        Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -        Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -        Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -        Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +        this.willShowSub = Keyboard.addListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> +        this.didShowSub = Keyboard.addListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> +        this.willHideSub = Keyboard.addListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> +        this.didHideSub = Keyboard.addListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
>     }
> };
> this.detachKeyboardListeners = () => {
>     const { invertibleScrollViewProps: invertibleProps } = this.props;
> -    Keyboard.removeListener('keyboardWillShow', invertibleProps.onKeyboardWillShow);
> -    Keyboard.removeListener('keyboardDidShow', invertibleProps.onKeyboardDidShow);
> -    Keyboard.removeListener('keyboardWillHide', invertibleProps.onKeyboardWillHide);
> -    Keyboard.removeListener('keyboardDidHide', invertibleProps.onKeyboardDidHide);
> +    this.willShowSub?.remove();
> +    this.didShowSub?.remove();
> +    this.willHideSub?.remove();
> +    this.didHideSub?.remove();
> };

Hi, i dont think modify lib is good solution, i want to keep library to lasted version always

**Comment by trancongdung12** [comment] 2022-04-25 02:30
I have the same issue :(

**Comment by Yogesh-Dubey-Ayesavi** [comment] 2022-05-17 19:47
@AMoktar proceed as mentioned above.
