### ISSUE TITLE
expo.io demo does not work

### ISSUE THREAD

**Issue by sidhant** [FaridSafi/react-native-gifted-chat#1233] opened 2019-05-19 03:00 UTC
#### Issue Description

Wanted to give the demo on expo.io that is linked from the Github repo's main page a try but failed.

`Device: (1052:881) Unable to resolve module 'module://react-native/Libraries/Image/resolveAssetSource.js'
  Evaluating module://react-native/Libraries/Image/resolveAssetSource.js
  Evaluating module://react-native-gifted-chat.js
  Evaluating module://App.js.js
  Loading module://App.js`

#### Steps to Reproduce / Code Snippets

Follow the link to expo.io demo. https://snack.expo.io/@xcarpentier/gifted-chat

#### Expected Results

Demo works similar to the GIF on repo's main page.

**Comment by ajrn-riguy** [comment] 2019-06-18 20:29
+1
Trying to build out a basic example to explain another issue and can't get a snack to work.

**Comment by sidhant** [comment] 2019-06-19 18:28
I worked around it by rolling back to a previous release version. Code changes were performed since then which broke expo.io compatibility.
On expo.io, here is my package.json

`{
  "dependencies": {
    "prop-types": "15.6.2",
    "react-native-gifted-chat": "0.7.0"
  }
}`

**Comment by suryaphani1729** [comment] 2019-06-21 11:23
> I worked around it by rolling back to a previous release version. Code changes were performed since then which broke expo.io compatibility.
> On expo.io, here is my package.json
> 
> `{ "dependencies": { "prop-types": "15.6.2", "react-native-gifted-chat": "0.7.0" } }`

Thank you. It Works for me

**Comment by llamaluvr** [comment] 2019-06-25 15:39
This applies to basically any use of the latest version of Gifted Chat on Snack. I made a very minimal example here: https://snack.expo.io/@llamaluvr/gifted-chat-does-not-work-on-expo-issue and it has the same error.

It appears that the issue could be resolved by using React Native video from Expo, per https://github.com/react-native-community/react-native-video/issues/1474. However, I'm not sure how this is done in a way that is compatible with using Gifted Chat in bare RN, Expo, Snack, etc. And this seems like it may be just covering up the real problem. Why wouldn't Image.resolveAssetSource() be available/

**Comment by llamaluvr** [comment] 2019-06-25 15:45
UPDATE: I just confirmed it was working in Snack as of 0.9.0, but broke after that.

**Comment by jpaulomotta** [comment] 2019-07-16 14:29
Getting the same issue here:

```
Device: (1053:881) Unable to resolve module 'module://react-native/Libraries/Image/resolveAssetSource.js'
  Evaluating module://react-native/Libraries/Image/resolveAssetSource.js
  Evaluating module://react-native-gifted-chat.js
  Evaluating module://App.js.js
  Loading module://App.js
```

**Comment by x5engine** [comment] 2019-08-01 00:30
same issue :'(

**Closed** 2019-10-07 01:00 UTC
Labels: wontfix

**Comment by x5engine** [comment] 2019-10-09 15:35
bad bot

**Comment by javierfuentesm** [comment] 2019-10-21 02:57
bad bot x2 there is no answer yet
