### ISSUE TITLE
Text box not visible when keyboard active using expo

### ISSUE THREAD

**Issue by hahahatrick** [FaridSafi/react-native-gifted-chat#680] opened 2017-12-26 13:31 UTC
#### Issue Description

Text bot is invisible when keyboard active in android with expo. I'm using```forceGetKeyboardHeight={true}``` and the message content moves correctly but there is an empty space instead of the textbox.
![screenshot_2017-12-26-18-51-19-590_host exp exponent](https://user-images.githubusercontent.com/33310702/34357541-0452d2d0-ea6e-11e7-8969-40171900f65d.png)

![screenshot_2017-12-26-18-50-57-697_host exp exponent](https://user-images.githubusercontent.com/33310702/34357545-0d6870fa-ea6e-11e7-8472-bef51173c3c7.png)

#### Steps to Reproduce / Code Snippets

```
<GiftedChat
        messages={this.state.messages}
        forceGetKeyboardHeight={true}
        onSend={(messages) => this.onSend(messages)}
        user={{
          _id: 1,
        }}
      />
```

#### Expected Results

The text box should be visible.

#### Additional Information

* Nodejs version: 8.9.3
* React version: 16.0.0
* React Native version: expo react native sdk 23.0.0
* react-native-gifted-chat version: 0.3.0
* expo version: 23.0.0
* Platform(s) (iOS, Android, or both?): Tested on android

**Comment by xcarpentier** [comment] 2017-12-26 22:10
And if you remove props forceGetKeyboardHeight?

**Comment by hahahatrick** [comment] 2017-12-27 05:29
@xcarpentier Then the screen does not get resized, the view remains the same and keyboard comes over it. I'm was able to fix it by removing the props forceGetKeyboardHeight and using KeyboardSpacer

**Comment by AbhishekVG** [comment] 2017-12-28 17:22
@hahahatrick even after putting KeyboardSpacer,The issue is not resolving.
Can you correct the below code if you have resolved the issue

```
<GiftedChat
        messages={this.state.messages}
        keyboardSpacer={true}
        onSend={(messages) => this.onSend(messages)}
        user={{
          _id: 1,
        }}
 />
```

**Comment by bhavna18** [comment] 2017-12-29 04:55
I had the same issue , but in my case textInputBar was pushing above the keyboard but its view was coming partially. 
` <KeyboardAvoidingView behavior={'padding'} style={{flex:1}} keyboardVerticalOffset={30}>
<ChatBot/>
</KeyboardAvoidingView>`
fixed my problem.
Here <ChatBot/> is my component where I have called GiftedChat .
Hope this helps.

**Comment by wmonecke** [comment] 2018-01-20 11:23
Same issue here also only on Android.

"react": "16.0.0-alpha.12",
"react-native": "0.48.3",
"react-native-gifted-chat": "^0.2.7",

**Comment by davidbiller** [comment] 2018-01-22 23:00
Same with

"expo": "^24.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz"
(RN 0.52)
 "react-native-gifted-chat": "^0.2.7",

`
return (
      <GiftedChat

        messages={ChatsStore.messages.slice()}
        onSend={(messages) => this.onSend(messages)}
        user={{
          _id: UserStore.user.id,
          name: UserStore.user.firstname,
          avatar: UserStore.user.avatar
        }}
      />
    );
`

**Comment by xcarpentier** [comment] 2018-01-23 07:24
Hello,
Sorry about that.
There are almost 2 solution to fix it:
- adding KeyboardAvoidingView after GiftedChat 
- adding an opaque background status bar on app.json https://docs.expo.io/versions/latest/guides/configuration.html#androidstatusbar

**Comment by watadarkstar** [comment] 2018-03-30 19:49
@xcarpentier What do you mean by **after** `GiftedChat`? Like this:

```
<View>
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          user={{
              _id: 1
            }}
          forceGetKeyboardHeight
        />
      <KeyboardAvoidingView />
</View>
```

**Comment by akulah91** [comment] 2018-03-31 03:38
I got it.. Just do like this..
```
  <View  style={{flex:1,backgroundColor:"#990"}}>
      <GiftedChat
           
        messages={this.state.messages} 
        onSend={messages => this.onSend(messages)}
        user={{
          _id: 1,
        }}
          ></GiftedChat>
        
        <KeyboardAvoidingView />  
            </View>
```

**Comment by watadarkstar** [comment] 2018-04-02 14:31
@akulah91 

I was wondering if you get this issue where the messages disappear when you type things.

Here is my code:
```
<View style={{ flex: 1 }}>
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          user={{
              _id: 1
            }}
          forceGetKeyboardHeight
        />
        <KeyboardAvoidingView behavior="padding" keyboardVerticalOffset={80} />
      </View>
```

And this is what I mean:

![29955176_10156238416510120_1170559467_o](https://user-images.githubusercontent.com/3059371/38198848-6726ed8a-365c-11e8-85cb-b7972522efd8.jpg)

![29995019_10156238417015120_559957920_o](https://user-images.githubusercontent.com/3059371/38198859-6c771d64-365c-11e8-9180-eb0446a45c85.jpg)

CC: @xcarpentier

**Comment by akulah91** [comment] 2018-04-09 03:44
@watadarkstar that because you put **forceGetKeyboardHeight** on your code..

**Comment by akulah91** [comment] 2018-04-10 01:27
@watadarkstar  most welcome..

**Comment by brunokiafuka** [comment] 2018-09-19 12:55
> I got it.. Just do like this..
> 
> ```
>  <View  style={{flex:1}}>
>           <GiftedChat
> 
>             messages={this.state.messages} 
>             onSend={messages => this.onSend(messages)}
>             user={{
>               _id: 1,
>             }}
>               ></GiftedChat>
> 
>             <KeyboardAvoidingView behavior={'padding'} keyboardVerticalOffset={80}/>
>         </View>
> ```
> need to declare flex to parent view to make it works. 👍

The code works fine but it adds a padding on iOS, so we have to check which Plaform the app is running,  my fix was 👇🏾

```
<View style={{ flex: 1 }}>
        <GiftedChat
          messages={this.state.messages}
          onSend={this.onSend}
          user={{
              _id: 1
            }}
          forceGetKeyboardHeight
        />
       <KeyboardAvoidingView behavior={ Platform.OS === 'android' ? 'padding' :  null} keyboardVerticalOffset={80} />
      </View>

```

**Comment by nandiniparimi1107** [comment] 2018-12-17 22:10
Its not working for me. I tried using KeyboardAvoidingView but still keyboard overlaps the text input

**Comment by brunokiafuka** [comment] 2018-12-17 22:46
Hi @nandiniparimi1107, here are the properties I've used in one of my projects and it's been working fine for both android and ios:

```javascript
 <GiftedChat
          renderAvatarOnTop={true}
          messages={this.state.messages}
           onSend={this.onSend}
          user={{
            _id: 1,
            name: this.state.name,
            avatar: this.state.imageUrl
          }}
          listViewProps={
            {
              onEndReached: this.onEndReached,
              onEndReachedThreshold: -5,
              onMomentumScrollBegin: this.onMomentumScrollBegin
            }}
        />
```

**Closed** 2019-02-23 00:09 UTC
Labels: wontfix

**Comment by hadpro24** [comment] 2019-05-21 17:03
Why use 80 ? I must use 190 so that it is clearly visible, Is there not a value that is noted for any device?

**Comment by nppull** [comment] 2019-09-06 03:57
> Why use 80 ? I must use 190 so that it is clearly visible, Is there not a value that is noted for any device?

yes my friend, i use 150

**Comment by RemusRD** [comment] 2019-09-11 22:12
I use it like this:
 `<KeyboardAvoidingView style={{flex: 1}} behavior={"padding"}
                                      keyboardVerticalOffset={Header.HEIGHT + StatusBar.currentHeight} enabled={Platform.OS === 'android'} >
                    <GiftedChat
                        messages={messages}
                        onSend={newMessages => onSend(newMessages)}
                        user=
                            {{
                                _id: 1,
                            }}
                        inverted={false}
                    />
                </KeyboardAvoidingView>`

**Comment by alexander0205** [comment] 2019-12-26 01:21
> I got it.. Just do like this..
> 
> ```
>  <View  style={{flex:1}}>
>           <GiftedChat
> 
>             messages={this.state.messages} 
>             onSend={messages => this.onSend(messages)}
>             user={{
>               _id: 1,
>             }}
>               ></GiftedChat>
> 
>             <KeyboardAvoidingView behavior={'padding'} keyboardVerticalOffset={80}/>
>         </View>
> ```
> 
> need to declare flex to parent view to make it works. 👍

thanks, worked form the first

**Comment by KrisShin** [comment] 2019-12-29 03:36
forceGetKeyboardHeight will move messgeArray up

**Comment by Wentris71** [comment] 2020-09-06 14:20
I got similar issue trying to implement my chat. 
![iPhone 11 (13 6) 2020-09-06 21-15-30](https://user-images.githubusercontent.com/18560311/92327766-427d1900-f086-11ea-8f39-66023af401d5.png)

it was a pain to find a solution. For some people helped to set keyboardHidesTabBar as a prop to custom tab navigator but not for me. `tabBarOptions={{keyboardHidesTabBar: false}}`

My solution - I am using react-native-paper as an ui lib and they are provided Portal component which can render something within current screen but in different place. it works fine
<img width="427" alt="Screenshot 2020-09-06 at 21 20 07" src="https://user-images.githubusercontent.com/18560311/92327850-c59e6f00-f086-11ea-99ba-c3f936d86fea.png">

**Comment by fukemy** [comment] 2022-04-17 11:09
no solution work for me

**Comment by dchhetri** [comment] 2024-10-20 01:14
> Hello, Sorry about that. There are almost 2 solutions to fix it:
> 
> * adding KeyboardAvoidingView after GiftedChat
> * adding an opaque background status bar on app.json https://docs.expo.io/versions/latest/guides/configuration.html#androidstatusbar

This doesn't work anymore in with the latest expo (51) and react native (74.x). There is no consistent solution that works for the varying android devices. Some still hides the input. Some adds too much padding. Some not enough. If I render just a simple scroll view with text input or a Flatlist with textinput, I don't see the issues. So I suspect it's something internal to the code here. 

Still trying to find a solution.
