### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by vidhyalakshmirbt** [FaridSafi/react-native-gifted-chat#435] opened 2017-04-24 04:57 UTC
When the user opens the app first time or when app is no longer in background or running, keyboard handling is fine but When user opens the application from background, keyboard hides the text input.
both in android and iOS , how can this be handled?
@kfiroo any idea?

**Comment by brunocascio** [comment] 2017-10-14 01:15
Please, complete the issue guideline in order to help you.

Thanks!

**Comment by pulpdood** [comment] 2017-11-12 09:53
I get the same thing on Android - the keyboard hides the text input when the text input is clicked

![image](https://user-images.githubusercontent.com/13587944/32697739-60f1bf56-c7eb-11e7-9e7a-1d5ac69e4a8f.png)

**Comment by 6axter82** [comment] 2018-01-29 09:48
If someone solved this? Please, post your solution

**Comment by pulpdood** [comment] 2018-01-29 09:51
Try davista123's solution here: https://github.com/FaridSafi/react-native-gifted-chat/issues/578

Worked for me although my problem was a little different

**Comment by 6axter82** [comment] 2018-01-29 09:53
@pulpdood neither #578 or #680 helped me. no changes for iOS

**Comment by xcarpentier** [comment] 2018-01-29 10:39
Hello @6axter82,

To be able to reproduce, can you please fill those informations?
And the share your code too?

Thanks
```
Nodejs version: [FILL THIS OUT]
React version: [FILL THIS OUT]
React Native version: [FILL THIS OUT]
react-native-gifted-chat version: [FILL THIS OUT]
Platform(s) (iOS, Android, or both?): [FILL THIS OUT]
```

**Comment by 6axter82** [comment] 2018-01-29 13:39
@xcarpentier 

Nodejs version: v6.9.0
React version: 16.2.0
React Native version: 0.52.0
react-native-gifted-chat version: ^0.3.0
Platform(s) (iOS, Android, or both?): using both, but only iOS is broken

The behaviour: tapping input area toggles the keyboard on iOS and the text area swipes together with the keyboard. At the end of swipe, the text area and the whole chat view behind the keyboard jumps to the initial position at the bottom, the keyboard remains shown on the screen. now, typing any character but 'space' brings the textinput to the top of the keyboard. and sending works as expected. look the gif i attached:

![example](https://user-images.githubusercontent.com/13738101/35513088-288988e8-0502-11e8-8260-31143f742233.gif)

**Comment by xcarpentier** [comment] 2018-01-29 13:45
Which kind of customizations did you have?

**Comment by 6axter82** [comment] 2018-01-29 14:07
Why do you think it is smth with customisation? The android version works just as expected with this customisation,..

```
<GiftedChat
	text={this.state.text}
	style={{flex: 1}}
	messages={this.state.sortedEvents}
	onSend={(messages) => this._onMessageSend(messages)}
	onInputTextChanged={(text) => this._checkForMentions(text)}
	textInputProps={{}}
	dateFormat={strings.dateFormat}
	timeFormat={strings.timeFormat}
	placeholder={strings.placeholder}
	locale={strings.getLanguage()}
	showUserAvatar={true}
	renderAvatarOnTop={false}
	renderBubble={this.renderBubble}
	renderSystemMessage={this.renderSystemMessage}
	renderChatFooter={this.renderChatFooter}
	keyboardShouldPersistTaps='never'
	user={{
		_id: user.id,
		name: user.firstName,
		avatar: user.hasProfilePicture ? user.avatarUrl : null
	}}
/>
```

**Comment by xcarpentier** [comment] 2018-01-29 14:34
Just to be able to reproduce...

**Comment by 6axter82** [comment] 2018-01-29 14:52
@xcarpentier if you need more info for reproducing the bug, please let me know

**Comment by 6axter82** [comment] 2018-01-30 09:26
@davista123 thanks for your input but your proposal doesn't fix it, on Android it got even worse. Also I need a fix for an iOS

**Comment by 6axter82** [comment] 2018-01-30 12:22
@xcarpentier and @davista123 I have done my own fix, check it and give me some response if it is a candidate for the release. This fixes for me the iOS version, as my Android did work properly without any change.
The magic number 45 I have taken from scanning some tickets in the web. I can't find the source but someone suggested to use this value for the inputtext bar height.

Added the following to the code:
```
componentWillMount() {
	if (Platform.OS === 'ios') {
		this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow',
                      this._keyboardDidShow);
		this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide',
                      this._keyboardDidHide);
	}
}

_keyboardDidShow = (e) => {
	let keyboardHeight = e.endCoordinates.height;
	this.setState({
		minInputToolbarHeight: keyboardHeight + 45,
	});
}

_keyboardDidHide = () => {
	this.setState({
		minInputToolbarHeight: 45,
	});
}

componentWillUnmount() {
	if (Platform.OS === 'ios') {
		this.keyboardDidShowListener.remove();
		this.keyboardDidHideListener.remove();
	}
}

render() {
	let platformConf = Platform.OS === 'ios' ? {
		minInputToolbarHeight: this.state.minInputToolbarHeight,
		bottomOffset: 0,
	} : {};
	return (
		<GiftedChat
			text={this.state.text}
			style={{flex: 1}}
			messages={this.state.sortedEvents}
			onSend={(messages) => this._onMessageSend(messages)}
			onInputTextChanged={(text) => this._checkForMentions(text)}
			textInputProps={{}}
			dateFormat={strings.dateFormat}
			timeFormat={strings.timeFormat}
			placeholder={strings.placeholder}
			locale={strings.getLanguage()}
			showUserAvatar={true}
			renderAvatarOnTop={false}
			renderBubble={this.renderBubble}
			renderSystemMessage={this.renderSystemMessage}
			renderChatFooter={this.renderChatFooter}
			keyboardShouldPersistTaps='never'
			{...platformConf}
			user={{
				_id: user.id,
				name: user.firstName,
				avatar: user.hasProfilePicture ? user.avatarUrl : null
			}}/>
	);
}
```

**Comment by Osama92** [comment] 2019-01-07 12:37
use yarn add react-native-keyboard-spacer or npm install react-native-keyboard-spacer.

**Comment by tapz** [comment] 2019-01-16 11:36
@Osama92 For me react-native-keyboard-spacer just adds a keyboard size gap between the chat and the keyboard.

**Comment by 14bscsskazmi** [comment] 2019-03-05 11:51
I am facing the same issue but only in android, I think IOS issue has been resolved with the latest react updates. I never faced this issue in IOS. Facing only in android so any one having the solution in android? please help!

**Closed** 2019-05-11 12:28 UTC
Labels: need-more-info, waiting-response, wontfix

**Comment by siddh1004** [comment] 2019-06-04 14:44
<View  style={{flex:1}}>
          <GiftedChat

            messages={this.state.messages}
            onSend={messages => this.onSend(messages)}
            user={{
              _id: 1,
            }}
              ></GiftedChat>

            <KeyboardAvoidingView behavior={'padding'}/>
        </View>

**Comment by adamsolomon1986** [comment] 2019-10-26 22:58
any updates on this?

**Comment by mkhoussid** [comment] 2019-10-29 12:39
Seems to be an issue for Expo and Android. Issue described here: https://stackoverflow.com/questions/58606815/issue-with-gifted-chat-the-messages-jump-up-the-screen-on-text-input

**Comment by azor0** [comment] 2020-01-20 12:27
Has anyone fixed this yet?

**Comment by zholmes1** [comment] 2020-07-29 15:37
I would like to leave the solution that I created since this issue was a real pain for me. I tried all combinations of `KeyboardAvoidingView` with all different kinds of props, the `forceGetKeyboardHeight` and anything else I could find on the internet. Nothing worked.

Here was my solution:

```
const [paddingBottom, setPaddingBottom] = useState(0)

useEffect(() => {
  if (Platform.OS !== 'android' || __DEV__) {
    return
  }

  const keyboardShowListener = Keyboard.addListener(keyboardDidShow', event => {
    setPaddingBottom(event.endCoordinates.height + Constants.statusBarHeight)
  })
  
  const keyboardHideListener = Keyboard.addListener('keyboardDidHide', () => {
    setPaddingBottom(0)
  })

  return () => {
    keyboardShowListener.remove()
    keyboardHideListener.remove()
  }
}, [])
```

Then wrap up your GiftedChat view with the padding

```
<View style={{flex: 1, paddingBottom}}>
  <GiftedChat ...
```

This was the only way I could fix my issue.

**Comment by hugoh59** [comment] 2020-10-28 13:50
Same issue here

**Comment by akhilsanker** [comment] 2020-11-02 07:52
Hi,
Same issue
Any solution?

Thanks

**Comment by ilaven** [comment] 2020-12-07 10:53
I am facing the same issue but only in **android**.

**Comment by woodcockjosh** [comment] 2020-12-29 20:11
I had same issue. It turns out I had `flexGrow: 1` on the input which was causing the problem for me.

**Comment by TriLuong** [comment] 2021-04-01 12:56
I added `android:windowSoftInputMode="adjustResize"` on `AndroidManifest.xml`, and it worked for me. There is an instruction `Notes for Android`  in `README`

**Comment by israromar** [comment] 2021-08-14 16:15
I solved it by simply making use of `minInputToolbarHeight` property with `platformConf` as suggested by @6axter82 
works like a charm.

`render() {
	let platformConf = Platform.OS === 'ios' ? {
		minInputToolbarHeight: 40,
		bottomOffset: 0,
	} : {};
	return (
		<GiftedChat
			text={this.state.text}
			style={{flex: 1}}
			messages={this.state.sortedEvents}
			onSend={(messages) => this._onMessageSend(messages)}
			onInputTextChanged={(text) => this._checkForMentions(text)}
			textInputProps={{}}
			dateFormat={strings.dateFormat}
			timeFormat={strings.timeFormat}
			placeholder={strings.placeholder}
			locale={strings.getLanguage()}
			showUserAvatar={true}
			renderAvatarOnTop={false}
			renderBubble={this.renderBubble}
			renderSystemMessage={this.renderSystemMessage}
			renderChatFooter={this.renderChatFooter}
			keyboardShouldPersistTaps='never'
			{...platformConf}
			user={{
				_id: user.id,
				name: user.firstName,
				avatar: user.hasProfilePicture ? user.avatarUrl : null
			}}/>
	);
}`

**Comment by cisplRejjak** [comment] 2022-06-08 15:13
load old chat history after gifted chat is fully initialized, by using setTimeout with 2-sec delay at least

its works for me

setTimeout(()=>{
            this.getPreviousChat();
        },3000)

**Comment by mudin** [comment] 2022-12-17 10:48
I fixed by adding `KeyboardAvoidingView`

```
<KeyboardAvoidingView
    flex={1}
    enabled={Platform.OS === 'android'}
    behavior="padding"
  >
    <GiftedChat
      ....  
    />
  </KeyboardAvoidingView>
```

Note that KeyboardAvoidingView is imported from `native-base`.
you can import from `react-native` directly

**Comment by kyushuInnovation** [comment] 2023-11-09 02:29
Has this problem been resolved? I'm still having the same issue on Android.

**Comment by alextbogdanov** [comment] 2025-02-01 22:29
This really fixed it for me:
https://medium.com/@islamrustamov/one-of-the-many-react-natives-textinput-problem-on-android-e4c9915acbc6
